package main

import (
	"context"
	"fmt"
	"log"
	"net/http"
	"os"
	"os/signal"
	"path/filepath"
	"syscall"

	"github.com/gin-gonic/gin"

	"github.com/suprimkhatri77/turgorepo/backend/internal/config"
	"github.com/suprimkhatri77/turgorepo/backend/internal/database"
	"github.com/suprimkhatri77/turgorepo/backend/internal/middleware"
	"github.com/suprimkhatri77/turgorepo/backend/internal/repository"
	"github.com/suprimkhatri77/turgorepo/backend/internal/routes"
)

func main() {
	cfg, err := config.Load()
	if err != nil {
		log.Fatalf("config: %v", err)
	}

	gin.SetMode(cfg.GinMode)

	if cfg.DatabaseURL == "" {
		log.Fatal("config: DATABASE_URL is required (set it in .env or environment)")
	}

	ctx := context.Background()
	db, err := database.New(ctx, cfg.DatabaseURL)
	if err != nil {
		log.Fatalf("database: %v", err)
	}
	defer db.Close()

	// Path to openapi.json (generated by packages/openapi, consumed at runtime)
	openapiPath := os.Getenv("OPENAPI_PATH")
	if openapiPath == "" {
		openapiPath = filepath.Join("openapi.json")
	}

	r := gin.New()
	r.Use(middleware.Recovery())
	r.Use(gin.Logger())
	r.Use(middleware.CORS())

	routes.Setup(r, routes.Config{
		TodoRepo:     repository.NewTodoRepository(db.Pool),
		OpenAPIPath:  openapiPath,
	})

	srv := &http.Server{
		Addr:    fmt.Sprintf(":%d", cfg.Port),
		Handler: r,
	}

	go func() {
		log.Printf("server listening on %s", srv.Addr)
		if err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			log.Fatalf("listen: %v", err)
		}
	}()

	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit
	log.Println("shutting down...")
	if err := srv.Shutdown(context.Background()); err != nil {
		log.Printf("server shutdown: %v", err)
	}
	log.Println("server stopped")
}
