// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type User = {
    id: string;
    name: string;
    email: string;
    role: 'superadmin' | 'admin' | 'staff' | 'member';
    image_url?: string;
};

export type RegisterBody = {
    name: string;
    email: string;
    password: string;
};

export type LoginBody = {
    email: string;
    password: string;
};

export type HealthResponse = {
    success: true;
    message: string;
    code?: 'INTERNAL_SERVER_ERROR' | 'VALIDATION_FAILED' | 'UNAUTHORIZED' | 'INVALID_PAGE_PARAMETER' | 'INVALID_ID_FORMAT' | 'INVALID_QUERY_PARAM' | 'PAGE_NOT_FOUND' | 'INVALID_CREDENTIALS' | 'INVALID_EMAIL' | 'INVALID_PASSWORD' | 'INVALID_TOKEN' | 'TOKEN_EXPIRED' | 'TOKEN_NOT_PROVIDED' | 'TOKEN_INVALID' | 'FORBIDDEN' | 'USER_NOT_FOUND' | 'USER_ALREADY_EXISTS';
    errors?: Array<{
        code: string;
        field?: string;
        message: string;
    }>;
    meta?: unknown;
};

export type AuthUserResponse = {
    success: true;
    message: string;
    code?: 'INTERNAL_SERVER_ERROR' | 'VALIDATION_FAILED' | 'UNAUTHORIZED' | 'INVALID_PAGE_PARAMETER' | 'INVALID_ID_FORMAT' | 'INVALID_QUERY_PARAM' | 'PAGE_NOT_FOUND' | 'INVALID_CREDENTIALS' | 'INVALID_EMAIL' | 'INVALID_PASSWORD' | 'INVALID_TOKEN' | 'TOKEN_EXPIRED' | 'TOKEN_NOT_PROVIDED' | 'TOKEN_INVALID' | 'FORBIDDEN' | 'USER_NOT_FOUND' | 'USER_ALREADY_EXISTS';
    errors?: Array<{
        code: string;
        field?: string;
        message: string;
    }>;
    meta?: unknown;
    data: {
        id: string;
        name: string;
        email: string;
        role: 'superadmin' | 'admin' | 'staff' | 'member';
        image_url?: string;
    };
};

export type MeResponse = {
    success: true;
    message: string;
    code?: 'INTERNAL_SERVER_ERROR' | 'VALIDATION_FAILED' | 'UNAUTHORIZED' | 'INVALID_PAGE_PARAMETER' | 'INVALID_ID_FORMAT' | 'INVALID_QUERY_PARAM' | 'PAGE_NOT_FOUND' | 'INVALID_CREDENTIALS' | 'INVALID_EMAIL' | 'INVALID_PASSWORD' | 'INVALID_TOKEN' | 'TOKEN_EXPIRED' | 'TOKEN_NOT_PROVIDED' | 'TOKEN_INVALID' | 'FORBIDDEN' | 'USER_NOT_FOUND' | 'USER_ALREADY_EXISTS';
    errors?: Array<{
        code: string;
        field?: string;
        message: string;
    }>;
    meta?: unknown;
    data: {
        id: string;
        name: string;
        email: string;
        role: 'superadmin' | 'admin' | 'staff' | 'member';
        image_url?: string;
    };
};

export type AuthSuccessResponse = {
    success: true;
    message: string;
    code?: 'INTERNAL_SERVER_ERROR' | 'VALIDATION_FAILED' | 'UNAUTHORIZED' | 'INVALID_PAGE_PARAMETER' | 'INVALID_ID_FORMAT' | 'INVALID_QUERY_PARAM' | 'PAGE_NOT_FOUND' | 'INVALID_CREDENTIALS' | 'INVALID_EMAIL' | 'INVALID_PASSWORD' | 'INVALID_TOKEN' | 'TOKEN_EXPIRED' | 'TOKEN_NOT_PROVIDED' | 'TOKEN_INVALID' | 'FORBIDDEN' | 'USER_NOT_FOUND' | 'USER_ALREADY_EXISTS';
    errors?: Array<{
        code: string;
        field?: string;
        message: string;
    }>;
    meta?: unknown;
};

export type ApiErrorResponse = {
    success: false;
    message: string;
    code: string;
    errors?: Array<{
        code: string;
        field?: string;
        message: string;
    }>;
};

export type GetApiV1HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health';
};

export type GetApiV1HealthResponses = {
    /**
     * Server is healthy
     */
    200: HealthResponse;
};

export type GetApiV1HealthResponse = GetApiV1HealthResponses[keyof GetApiV1HealthResponses];

export type PostApiV1AuthRegisterData = {
    body?: RegisterBody;
    path?: never;
    query?: never;
    url: '/api/v1/auth/register';
};

export type PostApiV1AuthRegisterErrors = {
    /**
     * Validation failed
     */
    400: ApiErrorResponse;
    /**
     * User already exists
     */
    409: ApiErrorResponse;
    /**
     * Internal server error
     */
    500: ApiErrorResponse;
};

export type PostApiV1AuthRegisterError = PostApiV1AuthRegisterErrors[keyof PostApiV1AuthRegisterErrors];

export type PostApiV1AuthRegisterResponses = {
    /**
     * Registration successful
     */
    201: AuthUserResponse;
};

export type PostApiV1AuthRegisterResponse = PostApiV1AuthRegisterResponses[keyof PostApiV1AuthRegisterResponses];

export type PostApiV1AuthLoginData = {
    body?: LoginBody;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type PostApiV1AuthLoginErrors = {
    /**
     * Validation failed
     */
    400: ApiErrorResponse;
    /**
     * Invalid credentials
     */
    401: ApiErrorResponse;
    /**
     * Internal server error
     */
    500: ApiErrorResponse;
};

export type PostApiV1AuthLoginError = PostApiV1AuthLoginErrors[keyof PostApiV1AuthLoginErrors];

export type PostApiV1AuthLoginResponses = {
    /**
     * Logged in successfully
     */
    200: AuthUserResponse;
};

export type PostApiV1AuthLoginResponse = PostApiV1AuthLoginResponses[keyof PostApiV1AuthLoginResponses];

export type PostApiV1AuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type PostApiV1AuthLogoutErrors = {
    /**
     * Internal server error
     */
    500: ApiErrorResponse;
};

export type PostApiV1AuthLogoutError = PostApiV1AuthLogoutErrors[keyof PostApiV1AuthLogoutErrors];

export type PostApiV1AuthLogoutResponses = {
    /**
     * Logged out successfully
     */
    200: AuthSuccessResponse;
};

export type PostApiV1AuthLogoutResponse = PostApiV1AuthLogoutResponses[keyof PostApiV1AuthLogoutResponses];

export type PostApiV1AuthRefreshData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/refresh';
};

export type PostApiV1AuthRefreshErrors = {
    /**
     * Missing or invalid refresh token
     */
    401: ApiErrorResponse;
    /**
     * Internal server error
     */
    500: ApiErrorResponse;
};

export type PostApiV1AuthRefreshError = PostApiV1AuthRefreshErrors[keyof PostApiV1AuthRefreshErrors];

export type PostApiV1AuthRefreshResponses = {
    /**
     * Tokens refreshed successfully
     */
    200: AuthSuccessResponse;
};

export type PostApiV1AuthRefreshResponse = PostApiV1AuthRefreshResponses[keyof PostApiV1AuthRefreshResponses];

export type GetApiV1AuthMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/me';
};

export type GetApiV1AuthMeErrors = {
    /**
     * Invalid user ID format
     */
    400: ApiErrorResponse;
    /**
     * Missing or invalid access token
     */
    401: ApiErrorResponse;
    /**
     * Insufficient permissions
     */
    403: ApiErrorResponse;
    /**
     * User not found
     */
    404: ApiErrorResponse;
    /**
     * Internal server error
     */
    500: ApiErrorResponse;
};

export type GetApiV1AuthMeError = GetApiV1AuthMeErrors[keyof GetApiV1AuthMeErrors];

export type GetApiV1AuthMeResponses = {
    /**
     * Valid session
     */
    200: MeResponse;
};

export type GetApiV1AuthMeResponse = GetApiV1AuthMeResponses[keyof GetApiV1AuthMeResponses];
